# Generated by Django 3.2.23 on 2023-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name',
        ),
        migrations.AddField(
            model_name='entry',
            name='nick_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
