# Generated by Django 3.2.23 on 2023-11-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20231104_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['created_on'], 'verbose_name': 'Player'},
        ),
    ]
