# Generated by Django 3.2.23 on 2023-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20231112_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='nick_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
