# Generated by Django 3.2.23 on 2023-11-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_entry_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='nick_name',
            field=models.CharField(choices=[('Warlord', 'Warlord'), ('King', 'King')], default='', max_length=50),
        ),
    ]
