# Generated by Django 3.2.23 on 2023-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_entry_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='email',
        ),
        migrations.AlterField(
            model_name='entry',
            name='nick_name',
            field=models.CharField(choices=[('CodeWarrior', 'CodeWarrior'), ('SyntaxSlayer', 'SyntaxSlayer'), ('LogicChampion', 'LogicChampion'), ('ByteBrawler', 'ByteBrawler'), ('BinaryNinja', 'BinaryNinja'), ('AlgorithmMaster', 'AlgorithmMaster'), ('PythonWhistler', 'PythonWhistler'), ('DjangoEater', 'DjangoEater'), ('JavaDriver', 'JavaDriver')], default='', max_length=50),
        ),
    ]
